name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código (default depth)
        uses: actions/checkout@v3
        # fetch-depth: 1 por defecto

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm run test -- --watch=false

      - name: Build
        run: npm run build

      - name: Subir sourcemaps a Sentry
        if: success()
        uses: getsentry/action-release@v1
        with:
          environment: production
          version: ${{ github.sha }}
          sourcemaps: "./dist/assets"
          set_commits: "auto"
          ignore_missing: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: https://sentry.io/
